<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE class [
        <!ELEMENT class (student+)>
        <!ELEMENT student (firstname,lastname,nickname,marks)>
        <!ATTLIST student rollno CDATA #REQUIRED>
        <!ELEMENT firstname (#PCDATA) >
        <!ELEMENT lastname (#PCDATA) >
        <!ELEMENT nickname (#PCDATA) >
        <!ELEMENT marks (#PCDATA) >
        ]>
<class>
    <student rollno="393">
        <firstname>cxx1</firstname>
        <lastname>Bob1</lastname>
        <nickname>stars1</nickname>
        <marks>85</marks>
    </student>
    <student rollno="493">
        <firstname>cxx2</firstname>
        <lastname>Bob2</lastname>
        <nickname>stars2</nickname>
        <marks>85</marks>
    </student>
    <student rollno="593">
        <firstname>cxx3</firstname>
        <lastname>Bob3</lastname>
        <nickname>stars3</nickname>
        <marks>85</marks>
    </student>
</class>